name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: pushpak-256/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ e7a7f23e-3dca-4ed6-b77a-540b39f2e742 }}
            SHOW_TITLE: true
            COMMIT_MESSAGE: 🤖 Update Waka-Time
